# Site settings
title: Fern Roath
subtitle: Visual Designer & Illustrator
email: me@fernroath.com

baseurl: ""
url: "http://fernroath.com"

twitter_username: CalmPluto
instagram_username: hihellofern
linkedin_url: fernroath

logo: assets/logo.png

collections:
  portfolio:
    output: true

# Build settings
markdown: kramdown
