# Site settings
title: Fern Roath
subtitle: Designer & Illustrator
email: me@fernroath.com
  
baseurl: ""
url: "http://fernroath.com"

twitter_username: FernRoath
instagram_username: fernroath
linkedin_url: fernroath

resume: /assets/Fern_Roath-Designer_Illustrator-2016.pdf

logo: assets/logo.png

collections:
  portfolio:
    output: true

# Build settings
markdown: kramdown
